# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crucible < Formula
  desc "A declarative dotfile and system configuration manager"
  homepage "https://github.com/ryanwersal/crucible"
  version "0.1.2"
  license "GPL-3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/ryanwersal/crucible/releases/download/v0.1.2/crucible_0.1.2_darwin_amd64.tar.gz"
    sha256 "fad8f9c48b4de560ad217f366b326e1dd4faad750256f212593e320245589107"

    define_method(:install) do
      bin.install "crucible"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/ryanwersal/crucible/releases/download/v0.1.2/crucible_0.1.2_darwin_arm64.tar.gz"
    sha256 "1b272f3294197e47982b0b3b1a61a19e881b796664203939f520c91248690822"

    define_method(:install) do
      bin.install "crucible"
    end
  end

  depends_on :macos

  test do
    system bin/"crucible", "version"
  end
end
