# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crucible < Formula
  desc "A declarative dotfile and system configuration manager"
  homepage "https://github.com/ryanwersal/crucible"
  version "0.1.3"
  license "GPL-3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/ryanwersal/crucible/releases/download/v0.1.3/crucible_0.1.3_darwin_amd64.tar.gz"
    sha256 "6655f9ba1de7602a68f005a1ee7023ecf7c3fbdc979b66f99fc151f747103d08"

    define_method(:install) do
      bin.install "crucible"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/ryanwersal/crucible/releases/download/v0.1.3/crucible_0.1.3_darwin_arm64.tar.gz"
    sha256 "2938973ecf29c036f5f375c27fe7cffb6b181dc994ba2ca14177649235a844f4"

    define_method(:install) do
      bin.install "crucible"
    end
  end

  depends_on :macos

  test do
    system bin/"crucible", "version"
  end
end
