# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nepenthe < Formula
  desc "Selective forgetfulness for macOS Time Machine"
  homepage "https://github.com/ryanwersal/nepenthe"
  version "0.1.0"
  license "GPL-3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/ryanwersal/nepenthe/releases/download/v0.1.0/nepenthe_0.1.0_darwin_amd64.tar.gz"
    sha256 "69b20045c5b839be940141ce3a94a98b7cab4c908514de82e179f53d6e333ac2"

    define_method(:install) do
      bin.install "nepenthe"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/ryanwersal/nepenthe/releases/download/v0.1.0/nepenthe_0.1.0_darwin_arm64.tar.gz"
    sha256 "dd4a3a26a2771c8911b52d797f851bd04ab723b468affad58838532dd98dd4e2"

    define_method(:install) do
      bin.install "nepenthe"
    end
  end

  depends_on :macos

  test do
    system bin/"nepenthe", "version"
  end
end
