# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nepenthe < Formula
  desc "Selective forgetfulness for macOS Time Machine"
  homepage "https://github.com/ryanwersal/nepenthe"
  version "0.1.2"
  license "GPL-3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/ryanwersal/nepenthe/releases/download/v0.1.2/nepenthe_0.1.2_darwin_amd64.tar.gz"
    sha256 "024a1e1111c303e2e2b9df0d2c00546abe3dfcd16904c87de40a45102d2990ca"

    define_method(:install) do
      bin.install "nepenthe"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/ryanwersal/nepenthe/releases/download/v0.1.2/nepenthe_0.1.2_darwin_arm64.tar.gz"
    sha256 "b3bc4a5289b69673c29ef13547c54dcefa25038c19f52e4525a42b1d5ca62e09"

    define_method(:install) do
      bin.install "nepenthe"
    end
  end

  depends_on :macos

  service do
    run [opt_bin/"nepenthe", "scan", "--accept-consents", "--log-format", "json"]
    run_type :interval
    interval 86400
    log_path var/"log/nepenthe/stdout.log"
    error_log_path var/"log/nepenthe/stderr.log"
  end

  test do
    system bin/"nepenthe", "version"
  end
end
