# This file was generated by GoReleaser. DO NOT EDIT.
cask "crucible" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "crucible"], chdir: ".", must_succeed: false
    end
  end

  version "0.2.14"

  on_macos do
    on_intel do
      url "https://github.com/ryanwersal/crucible/releases/download/v#{version}/crucible_#{version}_darwin_amd64.tar.gz"
      sha256 "b5700fe339fde150e6fcdd80f705c698d1a307a567af2718dbb32eb398acc148"
    end
    on_arm do
      url "https://github.com/ryanwersal/crucible/releases/download/v#{version}/crucible_#{version}_darwin_arm64.tar.gz"
      sha256 "afe93f68056fb758bb034053d8ce60090bb099cefb472cb4665055f0981c969c"
    end
  end

  name "crucible"
  desc "A declarative dotfile and system configuration manager"
  homepage "https://github.com/ryanwersal/crucible"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crucible"

  # No zap stanza required

end
