# This file was generated by GoReleaser. DO NOT EDIT.
cask "crucible" do
  version "0.2.8"

  on_macos do
    on_intel do
      url "https://github.com/ryanwersal/crucible/releases/download/v#{version}/crucible_#{version}_darwin_amd64.tar.gz"
      sha256 "3aa7f9fd4e81eacfedb85a6c9f58b19378f6721fcf61dd1014ed7257dd5a5a96"
    end
    on_arm do
      url "https://github.com/ryanwersal/crucible/releases/download/v#{version}/crucible_#{version}_darwin_arm64.tar.gz"
      sha256 "fb4aca3fa3af43f774d5a9247a66cf49ff823c3a9c29d8193f9ca7828e7a8eca"
    end
  end

  name "crucible"
  desc "A declarative dotfile and system configuration manager"
  homepage "https://github.com/ryanwersal/crucible"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crucible"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crucible"]
    end
  end

  # No zap stanza required

end
