# This file was generated by GoReleaser. DO NOT EDIT.
cask "crucible" do
  version "0.2.3"

  on_macos do
    on_intel do
      url "https://github.com/ryanwersal/crucible/releases/download/v#{version}/crucible_#{version}_darwin_amd64.tar.gz"
      sha256 "4b7b2d35b092dac463d4507a6baff2760788c7b90a80d4c40634e30ff720817c"
    end
    on_arm do
      url "https://github.com/ryanwersal/crucible/releases/download/v#{version}/crucible_#{version}_darwin_arm64.tar.gz"
      sha256 "22e69377c668033c158c5f8df87f47385f6dfc25908efbeefc3f6299079a5548"
    end
  end

  name "crucible"
  desc "A declarative dotfile and system configuration manager"
  homepage "https://github.com/ryanwersal/crucible"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crucible"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crucible"]
    end
  end

  # No zap stanza required

end
