# This file was generated by GoReleaser. DO NOT EDIT.
cask "nepenthe" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "37bd9cb40a8b1530d846f8d290f3c675c14718712f8c30454bb473168dd46e00"
      url "https://github.com/ryanwersal/nepenthe/releases/download/v#{version}/nepenthe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e2fee6b856442706cbde3743012dc46591011ea87a6fb99cc5cbacccb4a1d37"
      url "https://github.com/ryanwersal/nepenthe/releases/download/v#{version}/nepenthe_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "nepenthe"
  desc "Selective forgetfulness for macOS Time Machine"
  homepage "https://github.com/ryanwersal/nepenthe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nepenthe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nepenthe"]
    end
  end

  # No zap stanza required

end
