# This file is generated by the Wand release workflow. DO NOT EDIT.
cask "wand" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "893ebd644b694a436129b595bef9a942ea010165f7d4cb6a0bf3c1098a09be35"
      url "https://github.com/ryanwersal/wand/releases/download/v#{version}/wand_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7f39ce84b1ecab1e9035c9dab60292975bfef3f455662f0fac94a748f9263ce6"
      url "https://github.com/ryanwersal/wand/releases/download/v#{version}/wand_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "Wand"
  desc "Read-only, agent-first CLI for the Wiz GraphQL API"
  homepage "https://github.com/ryanwersal/wand"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wand"
end
