# This file is generated by the Wand release workflow. DO NOT EDIT.
cask "wand" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "5fba905b6f8a65b82fd65d6968d024496814fbf8356a87c9602045728f3c711d"
      url "https://github.com/ryanwersal/wand/releases/download/v#{version}/wand_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "df9fb90958783d0e2a76539f1cc0e0b8d02301a8140bf8d205c7d1b9f46847e4"
      url "https://github.com/ryanwersal/wand/releases/download/v#{version}/wand_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "Wand"
  desc "Read-only, agent-first CLI for the Wiz GraphQL API"
  homepage "https://github.com/ryanwersal/wand"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wand"
end
